package projects

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	domain "github.com/chaitin/agent-compose/pkg/model"
	"github.com/chaitin/agent-compose/pkg/projectdef"
	"github.com/chaitin/agent-compose/pkg/schedulers"
)

func ProjectSchedulerTriggersAndScript(projectID, agentName, schedulerName string, scheduler *projectdef.NormalizedSchedulerSpec) ([]domain.SchedulerTrigger, string, error) {
	if scheduler == nil {
		return nil, "", fmt.Errorf("scheduler is required")
	}
	triggers := make([]domain.SchedulerTrigger, 0, len(scheduler.Triggers))
	seenNames := make(map[string]struct{}, len(scheduler.Triggers))
	var script strings.Builder
	script.WriteString("// Generated by agent-compose project scheduler reconcile.\n")
	for _, trigger := range scheduler.Triggers {
		if trigger.IncludesEvent() {
			script.WriteString(eventPromptFormatterSource)
			break
		}
	}
	for i, trigger := range scheduler.Triggers {
		name := strings.TrimSpace(trigger.Name)
		if name != "" {
			if _, ok := seenNames[name]; ok {
				return nil, "", fmt.Errorf("duplicate scheduler trigger name %q", name)
			}
			seenNames[name] = struct{}{}
		}
		id, err := StableSchedulerTriggerID(projectID, agentName, schedulerName, name, i)
		if err != nil {
			return nil, "", err
		}
		schedulerTrigger, registration, err := ProjectSchedulerTriggerAndRegistration(id, agentName, trigger)
		if err != nil {
			return nil, "", err
		}
		triggers = append(triggers, schedulerTrigger)
		script.WriteString(registration)
	}
	if len(triggers) == 0 {
		script.WriteString("function main() { return { status: \"idle\" }; }\n")
	}
	return triggers, script.String(), nil
}

func ProjectSchedulerTriggerAndRegistration(id, agentName string, trigger projectdef.NormalizedTriggerSpec) (domain.SchedulerTrigger, string, error) {
	prompt := strings.TrimSpace(trigger.Prompt)
	if prompt == "" {
		prompt = fmt.Sprintf("Run agent %s.", agentName)
	}
	promptExpression := JSStringLiteral(prompt)
	if trigger.IncludesEvent() {
		promptExpression = eventTriggerPromptExpression(prompt, strings.TrimSpace(trigger.Event.Topic))
	}
	agentCall := fmt.Sprintf("scheduler.agent(%s)", promptExpression)
	if trigger.SandboxPolicy != "" {
		agentCall = fmt.Sprintf("scheduler.agent(%s, { sandboxPolicy: %s })", promptExpression, JSStringLiteral(trigger.SandboxPolicy))
	}
	callback := fmt.Sprintf("async function(event) { return %s; }", agentCall)
	switch trigger.Kind {
	case "cron":
		specJSON, err := schedulers.SchedulerCronSpecJSON(trigger.Cron, trigger.Timezone)
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		options := ""
		if trigger.Timezone != "" {
			options = fmt.Sprintf(", { timezone: %s }", JSStringLiteral(trigger.Timezone))
		}
		return domain.SchedulerTrigger{
			ID:       id,
			Kind:     domain.SchedulerTriggerKindCron,
			Enabled:  true,
			SpecJSON: specJSON,
		}, fmt.Sprintf("scheduler.cron(%s, %s, %s%s);\n", JSStringLiteral(id), JSStringLiteral(trigger.Cron), callback, options), nil
	case "interval":
		interval, err := time.ParseDuration(trigger.Interval)
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		intervalMs := interval.Milliseconds()
		if intervalMs <= 0 {
			return domain.SchedulerTrigger{}, "", fmt.Errorf("interval trigger %s must be at least 1ms", id)
		}
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.SchedulerTriggerKindInterval, "interval": trigger.Interval})
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		return domain.SchedulerTrigger{
			ID:         id,
			Kind:       domain.SchedulerTriggerKindInterval,
			IntervalMs: intervalMs,
			Enabled:    true,
			SpecJSON:   specJSON,
		}, fmt.Sprintf("scheduler.interval(%s, %s, %d);\n", JSStringLiteral(id), callback, intervalMs), nil
	case "timeout":
		delay, err := time.ParseDuration(trigger.Timeout)
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		delayMs := delay.Milliseconds()
		if delayMs <= 0 {
			return domain.SchedulerTrigger{}, "", fmt.Errorf("timeout trigger %s must be at least 1ms", id)
		}
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.SchedulerTriggerKindTimeout, "timeout": trigger.Timeout})
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		return domain.SchedulerTrigger{
			ID:         id,
			Kind:       domain.SchedulerTriggerKindTimeout,
			IntervalMs: delayMs,
			Enabled:    true,
			SpecJSON:   specJSON,
		}, fmt.Sprintf("scheduler.timeout(%s, %s, %d);\n", JSStringLiteral(id), callback, delayMs), nil
	case "event":
		if trigger.Event == nil {
			return domain.SchedulerTrigger{}, "", fmt.Errorf("event trigger topic is required")
		}
		topic := strings.TrimSpace(trigger.Event.Topic)
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.SchedulerTriggerKindEvent, "topic": topic})
		if err != nil {
			return domain.SchedulerTrigger{}, "", err
		}
		return domain.SchedulerTrigger{
			ID:       id,
			Kind:     domain.SchedulerTriggerKindEvent,
			Topic:    topic,
			Enabled:  true,
			SpecJSON: specJSON,
		}, fmt.Sprintf("scheduler.on(%s, %s, %s);\n", JSStringLiteral(topic), JSStringLiteral(id), callback), nil
	default:
		return domain.SchedulerTrigger{}, "", fmt.Errorf("unsupported scheduler trigger kind %q", trigger.Kind)
	}
}

func JSStringLiteral(value string) string {
	data, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(data)
}
