package driver

import "testing"

func TestRuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSandboxProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSandboxDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	TestExecOutputFilterReportsKnownSeccompWarning(t)
	TestExecOutputFilterHandlesSplitWarning(t)
	TestExecOutputFilterPreservesRealStderr(t)
	TestExecOutputFilterKeepsStderrAfterWarning(t)
	testJupyterGuestCoverageWorkflow(t)
}

func TestIntegrationRuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSandboxProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSandboxDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	TestExecOutputFilterReportsKnownSeccompWarning(t)
	TestExecOutputFilterHandlesSplitWarning(t)
	TestExecOutputFilterPreservesRealStderr(t)
	TestExecOutputFilterKeepsStderrAfterWarning(t)
	testJupyterGuestCoverageWorkflow(t)
	TestValidateRuntimeDriverK8s(t)
	TestRuntimeDriverSupportsStoppedRuntimeRetention(t)
	TestDriverDefaultsForK8s(t)
	TestPrepareRuntimeMountManifestForK8sHasNoMounts(t)
}

func TestE2ERuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSandboxProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSandboxDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	TestExecOutputFilterReportsKnownSeccompWarning(t)
	TestExecOutputFilterHandlesSplitWarning(t)
	TestExecOutputFilterPreservesRealStderr(t)
	TestExecOutputFilterKeepsStderrAfterWarning(t)
	testJupyterGuestCoverageWorkflow(t)
	TestValidateRuntimeDriverK8s(t)
	TestRuntimeDriverSupportsStoppedRuntimeRetention(t)
	TestDriverDefaultsForK8s(t)
	TestPrepareRuntimeMountManifestForK8sHasNoMounts(t)
}
