-- The daemon connection an agent must use, declared as `llm_connection`.
--
-- Connection selection is otherwise a lookup: explicit connection -> the
-- default model's owning connection -> the unique connection bound to the
-- model -> the sole connection, and an ambiguous outcome is reported. Recording
-- the agent's explicit choice on the row is what makes the highest-precedence
-- level of that lookup reachable from declarative configuration, instead of
-- only from a request.
--
-- Empty keeps the previous behaviour: infer the connection from the model.
-- The agent-definition table is project_agent; migration 000005 dropped the
-- legacy agent_definition table and renamed the live one.
ALTER TABLE project_agent ADD COLUMN llm_connection TEXT NOT NULL DEFAULT '';
