package storage

import "testing"

func TestIntegrationTopicEventStoreWorkflow(t *testing.T) {
	TestConfigStoreCreateAndListTopicEvents(t)
	TestConfigStoreTopicEventIdempotency(t)
	TestConfigStorePendingAndPublishedTopicEvents(t)
	TestConfigStoreEventDeliveryDoesNotDowngradeRunOnDuplicateMatch(t)
	TestConfigStoreWebhookSourceCRUDAndTopicMatching(t)
	TestTopicEventModelAndStoreErrorBranches(t)
	testStoreAgentRunLegacyVMAndListWorkflows(t)
	testConfigStoreMigrationAndTimeParsingWorkflows(t)
}

func TestE2ETopicEventStoreWorkflow(t *testing.T) {
	TestConfigStoreCreateAndListTopicEvents(t)
	TestConfigStoreTopicEventIdempotency(t)
	TestConfigStorePendingAndPublishedTopicEvents(t)
	TestConfigStoreEventDeliveryDoesNotDowngradeRunOnDuplicateMatch(t)
	TestConfigStoreWebhookSourceCRUDAndTopicMatching(t)
	TestTopicEventModelAndStoreErrorBranches(t)
	testStoreAgentRunLegacyVMAndListWorkflows(t)
	testConfigStoreMigrationAndTimeParsingWorkflows(t)
}
