// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agentcompose/v2/agentcompose.proto

package agentcomposev2connect

import (
	v2 "agent-compose/proto/agentcompose/v2"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "agentcompose.v2.ProjectService"
	// RunServiceName is the fully-qualified name of the RunService service.
	RunServiceName = "agentcompose.v2.RunService"
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "agentcompose.v2.ArtifactService"
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "agentcompose.v2.EventService"
	// ExecServiceName is the fully-qualified name of the ExecService service.
	ExecServiceName = "agentcompose.v2.ExecService"
	// ImageServiceName is the fully-qualified name of the ImageService service.
	ImageServiceName = "agentcompose.v2.ImageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceValidateProjectProcedure is the fully-qualified name of the ProjectService's
	// ValidateProject RPC.
	ProjectServiceValidateProjectProcedure = "/agentcompose.v2.ProjectService/ValidateProject"
	// ProjectServiceApplyProjectProcedure is the fully-qualified name of the ProjectService's
	// ApplyProject RPC.
	ProjectServiceApplyProjectProcedure = "/agentcompose.v2.ProjectService/ApplyProject"
	// ProjectServiceGetProjectProcedure is the fully-qualified name of the ProjectService's GetProject
	// RPC.
	ProjectServiceGetProjectProcedure = "/agentcompose.v2.ProjectService/GetProject"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/agentcompose.v2.ProjectService/ListProjects"
	// ProjectServiceRemoveProjectProcedure is the fully-qualified name of the ProjectService's
	// RemoveProject RPC.
	ProjectServiceRemoveProjectProcedure = "/agentcompose.v2.ProjectService/RemoveProject"
	// ProjectServiceDiffProjectProcedure is the fully-qualified name of the ProjectService's
	// DiffProject RPC.
	ProjectServiceDiffProjectProcedure = "/agentcompose.v2.ProjectService/DiffProject"
	// ProjectServiceListProjectRevisionsProcedure is the fully-qualified name of the ProjectService's
	// ListProjectRevisions RPC.
	ProjectServiceListProjectRevisionsProcedure = "/agentcompose.v2.ProjectService/ListProjectRevisions"
	// ProjectServiceRollbackProjectRevisionProcedure is the fully-qualified name of the
	// ProjectService's RollbackProjectRevision RPC.
	ProjectServiceRollbackProjectRevisionProcedure = "/agentcompose.v2.ProjectService/RollbackProjectRevision"
	// ProjectServiceWatchProjectProcedure is the fully-qualified name of the ProjectService's
	// WatchProject RPC.
	ProjectServiceWatchProjectProcedure = "/agentcompose.v2.ProjectService/WatchProject"
	// RunServiceInvokeServiceProcedure is the fully-qualified name of the RunService's InvokeService
	// RPC.
	RunServiceInvokeServiceProcedure = "/agentcompose.v2.RunService/InvokeService"
	// RunServiceInvokeServiceStreamProcedure is the fully-qualified name of the RunService's
	// InvokeServiceStream RPC.
	RunServiceInvokeServiceStreamProcedure = "/agentcompose.v2.RunService/InvokeServiceStream"
	// RunServiceRunAgentProcedure is the fully-qualified name of the RunService's RunAgent RPC.
	RunServiceRunAgentProcedure = "/agentcompose.v2.RunService/RunAgent"
	// RunServiceRunAgentStreamProcedure is the fully-qualified name of the RunService's RunAgentStream
	// RPC.
	RunServiceRunAgentStreamProcedure = "/agentcompose.v2.RunService/RunAgentStream"
	// RunServiceGetRunProcedure is the fully-qualified name of the RunService's GetRun RPC.
	RunServiceGetRunProcedure = "/agentcompose.v2.RunService/GetRun"
	// RunServiceListRunsProcedure is the fully-qualified name of the RunService's ListRuns RPC.
	RunServiceListRunsProcedure = "/agentcompose.v2.RunService/ListRuns"
	// RunServiceStopRunProcedure is the fully-qualified name of the RunService's StopRun RPC.
	RunServiceStopRunProcedure = "/agentcompose.v2.RunService/StopRun"
	// RunServiceWatchRunProcedure is the fully-qualified name of the RunService's WatchRun RPC.
	RunServiceWatchRunProcedure = "/agentcompose.v2.RunService/WatchRun"
	// ArtifactServiceListArtifactsProcedure is the fully-qualified name of the ArtifactService's
	// ListArtifacts RPC.
	ArtifactServiceListArtifactsProcedure = "/agentcompose.v2.ArtifactService/ListArtifacts"
	// ArtifactServiceGetArtifactProcedure is the fully-qualified name of the ArtifactService's
	// GetArtifact RPC.
	ArtifactServiceGetArtifactProcedure = "/agentcompose.v2.ArtifactService/GetArtifact"
	// ArtifactServiceReadArtifactProcedure is the fully-qualified name of the ArtifactService's
	// ReadArtifact RPC.
	ArtifactServiceReadArtifactProcedure = "/agentcompose.v2.ArtifactService/ReadArtifact"
	// ArtifactServiceWriteArtifactProcedure is the fully-qualified name of the ArtifactService's
	// WriteArtifact RPC.
	ArtifactServiceWriteArtifactProcedure = "/agentcompose.v2.ArtifactService/WriteArtifact"
	// ArtifactServiceDeleteArtifactProcedure is the fully-qualified name of the ArtifactService's
	// DeleteArtifact RPC.
	ArtifactServiceDeleteArtifactProcedure = "/agentcompose.v2.ArtifactService/DeleteArtifact"
	// EventServicePublishEventProcedure is the fully-qualified name of the EventService's PublishEvent
	// RPC.
	EventServicePublishEventProcedure = "/agentcompose.v2.EventService/PublishEvent"
	// EventServiceListEventsProcedure is the fully-qualified name of the EventService's ListEvents RPC.
	EventServiceListEventsProcedure = "/agentcompose.v2.EventService/ListEvents"
	// EventServiceWatchEventsProcedure is the fully-qualified name of the EventService's WatchEvents
	// RPC.
	EventServiceWatchEventsProcedure = "/agentcompose.v2.EventService/WatchEvents"
	// ExecServiceExecProcedure is the fully-qualified name of the ExecService's Exec RPC.
	ExecServiceExecProcedure = "/agentcompose.v2.ExecService/Exec"
	// ExecServiceExecStreamProcedure is the fully-qualified name of the ExecService's ExecStream RPC.
	ExecServiceExecStreamProcedure = "/agentcompose.v2.ExecService/ExecStream"
	// ImageServiceListImagesProcedure is the fully-qualified name of the ImageService's ListImages RPC.
	ImageServiceListImagesProcedure = "/agentcompose.v2.ImageService/ListImages"
	// ImageServicePullImageProcedure is the fully-qualified name of the ImageService's PullImage RPC.
	ImageServicePullImageProcedure = "/agentcompose.v2.ImageService/PullImage"
	// ImageServiceInspectImageProcedure is the fully-qualified name of the ImageService's InspectImage
	// RPC.
	ImageServiceInspectImageProcedure = "/agentcompose.v2.ImageService/InspectImage"
	// ImageServiceRemoveImageProcedure is the fully-qualified name of the ImageService's RemoveImage
	// RPC.
	ImageServiceRemoveImageProcedure = "/agentcompose.v2.ImageService/RemoveImage"
)

// ProjectServiceClient is a client for the agentcompose.v2.ProjectService service.
type ProjectServiceClient interface {
	ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error)
	ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error)
	GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error)
	RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error)
	DiffProject(context.Context, *connect.Request[v2.DiffProjectRequest]) (*connect.Response[v2.DiffProjectResponse], error)
	ListProjectRevisions(context.Context, *connect.Request[v2.ListProjectRevisionsRequest]) (*connect.Response[v2.ListProjectRevisionsResponse], error)
	RollbackProjectRevision(context.Context, *connect.Request[v2.RollbackProjectRevisionRequest]) (*connect.Response[v2.RollbackProjectRevisionResponse], error)
	WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest]) (*connect.ServerStreamForClient[v2.WatchProjectResponse], error)
}

// NewProjectServiceClient constructs a client for the agentcompose.v2.ProjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		validateProject: connect.NewClient[v2.ValidateProjectRequest, v2.ValidateProjectResponse](
			httpClient,
			baseURL+ProjectServiceValidateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ValidateProject")),
			connect.WithClientOptions(opts...),
		),
		applyProject: connect.NewClient[v2.ApplyProjectRequest, v2.ApplyProjectResponse](
			httpClient,
			baseURL+ProjectServiceApplyProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ApplyProject")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v2.GetProjectRequest, v2.GetProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v2.ListProjectsRequest, v2.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		removeProject: connect.NewClient[v2.RemoveProjectRequest, v2.RemoveProjectResponse](
			httpClient,
			baseURL+ProjectServiceRemoveProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("RemoveProject")),
			connect.WithClientOptions(opts...),
		),
		diffProject: connect.NewClient[v2.DiffProjectRequest, v2.DiffProjectResponse](
			httpClient,
			baseURL+ProjectServiceDiffProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("DiffProject")),
			connect.WithClientOptions(opts...),
		),
		listProjectRevisions: connect.NewClient[v2.ListProjectRevisionsRequest, v2.ListProjectRevisionsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectRevisionsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjectRevisions")),
			connect.WithClientOptions(opts...),
		),
		rollbackProjectRevision: connect.NewClient[v2.RollbackProjectRevisionRequest, v2.RollbackProjectRevisionResponse](
			httpClient,
			baseURL+ProjectServiceRollbackProjectRevisionProcedure,
			connect.WithSchema(projectServiceMethods.ByName("RollbackProjectRevision")),
			connect.WithClientOptions(opts...),
		),
		watchProject: connect.NewClient[v2.WatchProjectRequest, v2.WatchProjectResponse](
			httpClient,
			baseURL+ProjectServiceWatchProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("WatchProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	validateProject         *connect.Client[v2.ValidateProjectRequest, v2.ValidateProjectResponse]
	applyProject            *connect.Client[v2.ApplyProjectRequest, v2.ApplyProjectResponse]
	getProject              *connect.Client[v2.GetProjectRequest, v2.GetProjectResponse]
	listProjects            *connect.Client[v2.ListProjectsRequest, v2.ListProjectsResponse]
	removeProject           *connect.Client[v2.RemoveProjectRequest, v2.RemoveProjectResponse]
	diffProject             *connect.Client[v2.DiffProjectRequest, v2.DiffProjectResponse]
	listProjectRevisions    *connect.Client[v2.ListProjectRevisionsRequest, v2.ListProjectRevisionsResponse]
	rollbackProjectRevision *connect.Client[v2.RollbackProjectRevisionRequest, v2.RollbackProjectRevisionResponse]
	watchProject            *connect.Client[v2.WatchProjectRequest, v2.WatchProjectResponse]
}

// ValidateProject calls agentcompose.v2.ProjectService.ValidateProject.
func (c *projectServiceClient) ValidateProject(ctx context.Context, req *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error) {
	return c.validateProject.CallUnary(ctx, req)
}

// ApplyProject calls agentcompose.v2.ProjectService.ApplyProject.
func (c *projectServiceClient) ApplyProject(ctx context.Context, req *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error) {
	return c.applyProject.CallUnary(ctx, req)
}

// GetProject calls agentcompose.v2.ProjectService.GetProject.
func (c *projectServiceClient) GetProject(ctx context.Context, req *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// ListProjects calls agentcompose.v2.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// RemoveProject calls agentcompose.v2.ProjectService.RemoveProject.
func (c *projectServiceClient) RemoveProject(ctx context.Context, req *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error) {
	return c.removeProject.CallUnary(ctx, req)
}

// DiffProject calls agentcompose.v2.ProjectService.DiffProject.
func (c *projectServiceClient) DiffProject(ctx context.Context, req *connect.Request[v2.DiffProjectRequest]) (*connect.Response[v2.DiffProjectResponse], error) {
	return c.diffProject.CallUnary(ctx, req)
}

// ListProjectRevisions calls agentcompose.v2.ProjectService.ListProjectRevisions.
func (c *projectServiceClient) ListProjectRevisions(ctx context.Context, req *connect.Request[v2.ListProjectRevisionsRequest]) (*connect.Response[v2.ListProjectRevisionsResponse], error) {
	return c.listProjectRevisions.CallUnary(ctx, req)
}

// RollbackProjectRevision calls agentcompose.v2.ProjectService.RollbackProjectRevision.
func (c *projectServiceClient) RollbackProjectRevision(ctx context.Context, req *connect.Request[v2.RollbackProjectRevisionRequest]) (*connect.Response[v2.RollbackProjectRevisionResponse], error) {
	return c.rollbackProjectRevision.CallUnary(ctx, req)
}

// WatchProject calls agentcompose.v2.ProjectService.WatchProject.
func (c *projectServiceClient) WatchProject(ctx context.Context, req *connect.Request[v2.WatchProjectRequest]) (*connect.ServerStreamForClient[v2.WatchProjectResponse], error) {
	return c.watchProject.CallServerStream(ctx, req)
}

// ProjectServiceHandler is an implementation of the agentcompose.v2.ProjectService service.
type ProjectServiceHandler interface {
	ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error)
	ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error)
	GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error)
	RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error)
	DiffProject(context.Context, *connect.Request[v2.DiffProjectRequest]) (*connect.Response[v2.DiffProjectResponse], error)
	ListProjectRevisions(context.Context, *connect.Request[v2.ListProjectRevisionsRequest]) (*connect.Response[v2.ListProjectRevisionsResponse], error)
	RollbackProjectRevision(context.Context, *connect.Request[v2.RollbackProjectRevisionRequest]) (*connect.Response[v2.RollbackProjectRevisionResponse], error)
	WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest], *connect.ServerStream[v2.WatchProjectResponse]) error
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ProjectService").Methods()
	projectServiceValidateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceValidateProjectProcedure,
		svc.ValidateProject,
		connect.WithSchema(projectServiceMethods.ByName("ValidateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceApplyProjectHandler := connect.NewUnaryHandler(
		ProjectServiceApplyProjectProcedure,
		svc.ApplyProject,
		connect.WithSchema(projectServiceMethods.ByName("ApplyProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetProjectHandler := connect.NewUnaryHandler(
		ProjectServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(projectServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceRemoveProjectHandler := connect.NewUnaryHandler(
		ProjectServiceRemoveProjectProcedure,
		svc.RemoveProject,
		connect.WithSchema(projectServiceMethods.ByName("RemoveProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceDiffProjectHandler := connect.NewUnaryHandler(
		ProjectServiceDiffProjectProcedure,
		svc.DiffProject,
		connect.WithSchema(projectServiceMethods.ByName("DiffProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectRevisionsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectRevisionsProcedure,
		svc.ListProjectRevisions,
		connect.WithSchema(projectServiceMethods.ByName("ListProjectRevisions")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceRollbackProjectRevisionHandler := connect.NewUnaryHandler(
		ProjectServiceRollbackProjectRevisionProcedure,
		svc.RollbackProjectRevision,
		connect.WithSchema(projectServiceMethods.ByName("RollbackProjectRevision")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceWatchProjectHandler := connect.NewServerStreamHandler(
		ProjectServiceWatchProjectProcedure,
		svc.WatchProject,
		connect.WithSchema(projectServiceMethods.ByName("WatchProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceValidateProjectProcedure:
			projectServiceValidateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceApplyProjectProcedure:
			projectServiceApplyProjectHandler.ServeHTTP(w, r)
		case ProjectServiceGetProjectProcedure:
			projectServiceGetProjectHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceRemoveProjectProcedure:
			projectServiceRemoveProjectHandler.ServeHTTP(w, r)
		case ProjectServiceDiffProjectProcedure:
			projectServiceDiffProjectHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectRevisionsProcedure:
			projectServiceListProjectRevisionsHandler.ServeHTTP(w, r)
		case ProjectServiceRollbackProjectRevisionProcedure:
			projectServiceRollbackProjectRevisionHandler.ServeHTTP(w, r)
		case ProjectServiceWatchProjectProcedure:
			projectServiceWatchProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ValidateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ApplyProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.GetProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.RemoveProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) DiffProject(context.Context, *connect.Request[v2.DiffProjectRequest]) (*connect.Response[v2.DiffProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.DiffProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjectRevisions(context.Context, *connect.Request[v2.ListProjectRevisionsRequest]) (*connect.Response[v2.ListProjectRevisionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ListProjectRevisions is not implemented"))
}

func (UnimplementedProjectServiceHandler) RollbackProjectRevision(context.Context, *connect.Request[v2.RollbackProjectRevisionRequest]) (*connect.Response[v2.RollbackProjectRevisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.RollbackProjectRevision is not implemented"))
}

func (UnimplementedProjectServiceHandler) WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest], *connect.ServerStream[v2.WatchProjectResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.WatchProject is not implemented"))
}

// RunServiceClient is a client for the agentcompose.v2.RunService service.
type RunServiceClient interface {
	InvokeService(context.Context, *connect.Request[v2.InvokeServiceRequest]) (*connect.Response[v2.InvokeServiceResponse], error)
	InvokeServiceStream(context.Context, *connect.Request[v2.InvokeServiceRequest]) (*connect.ServerStreamForClient[v2.RunStreamResponse], error)
	RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error)
	RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.ServerStreamForClient[v2.RunAgentStreamResponse], error)
	GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error)
	ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error)
	StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error)
	WatchRun(context.Context, *connect.Request[v2.WatchRunRequest]) (*connect.ServerStreamForClient[v2.RunStreamResponse], error)
}

// NewRunServiceClient constructs a client for the agentcompose.v2.RunService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("RunService").Methods()
	return &runServiceClient{
		invokeService: connect.NewClient[v2.InvokeServiceRequest, v2.InvokeServiceResponse](
			httpClient,
			baseURL+RunServiceInvokeServiceProcedure,
			connect.WithSchema(runServiceMethods.ByName("InvokeService")),
			connect.WithClientOptions(opts...),
		),
		invokeServiceStream: connect.NewClient[v2.InvokeServiceRequest, v2.RunStreamResponse](
			httpClient,
			baseURL+RunServiceInvokeServiceStreamProcedure,
			connect.WithSchema(runServiceMethods.ByName("InvokeServiceStream")),
			connect.WithClientOptions(opts...),
		),
		runAgent: connect.NewClient[v2.RunAgentRequest, v2.RunAgentResponse](
			httpClient,
			baseURL+RunServiceRunAgentProcedure,
			connect.WithSchema(runServiceMethods.ByName("RunAgent")),
			connect.WithClientOptions(opts...),
		),
		runAgentStream: connect.NewClient[v2.RunAgentRequest, v2.RunAgentStreamResponse](
			httpClient,
			baseURL+RunServiceRunAgentStreamProcedure,
			connect.WithSchema(runServiceMethods.ByName("RunAgentStream")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v2.GetRunRequest, v2.GetRunResponse](
			httpClient,
			baseURL+RunServiceGetRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v2.ListRunsRequest, v2.ListRunsResponse](
			httpClient,
			baseURL+RunServiceListRunsProcedure,
			connect.WithSchema(runServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[v2.StopRunRequest, v2.StopRunResponse](
			httpClient,
			baseURL+RunServiceStopRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
		watchRun: connect.NewClient[v2.WatchRunRequest, v2.RunStreamResponse](
			httpClient,
			baseURL+RunServiceWatchRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("WatchRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runServiceClient implements RunServiceClient.
type runServiceClient struct {
	invokeService       *connect.Client[v2.InvokeServiceRequest, v2.InvokeServiceResponse]
	invokeServiceStream *connect.Client[v2.InvokeServiceRequest, v2.RunStreamResponse]
	runAgent            *connect.Client[v2.RunAgentRequest, v2.RunAgentResponse]
	runAgentStream      *connect.Client[v2.RunAgentRequest, v2.RunAgentStreamResponse]
	getRun              *connect.Client[v2.GetRunRequest, v2.GetRunResponse]
	listRuns            *connect.Client[v2.ListRunsRequest, v2.ListRunsResponse]
	stopRun             *connect.Client[v2.StopRunRequest, v2.StopRunResponse]
	watchRun            *connect.Client[v2.WatchRunRequest, v2.RunStreamResponse]
}

// InvokeService calls agentcompose.v2.RunService.InvokeService.
func (c *runServiceClient) InvokeService(ctx context.Context, req *connect.Request[v2.InvokeServiceRequest]) (*connect.Response[v2.InvokeServiceResponse], error) {
	return c.invokeService.CallUnary(ctx, req)
}

// InvokeServiceStream calls agentcompose.v2.RunService.InvokeServiceStream.
func (c *runServiceClient) InvokeServiceStream(ctx context.Context, req *connect.Request[v2.InvokeServiceRequest]) (*connect.ServerStreamForClient[v2.RunStreamResponse], error) {
	return c.invokeServiceStream.CallServerStream(ctx, req)
}

// RunAgent calls agentcompose.v2.RunService.RunAgent.
func (c *runServiceClient) RunAgent(ctx context.Context, req *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error) {
	return c.runAgent.CallUnary(ctx, req)
}

// RunAgentStream calls agentcompose.v2.RunService.RunAgentStream.
func (c *runServiceClient) RunAgentStream(ctx context.Context, req *connect.Request[v2.RunAgentRequest]) (*connect.ServerStreamForClient[v2.RunAgentStreamResponse], error) {
	return c.runAgentStream.CallServerStream(ctx, req)
}

// GetRun calls agentcompose.v2.RunService.GetRun.
func (c *runServiceClient) GetRun(ctx context.Context, req *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRuns calls agentcompose.v2.RunService.ListRuns.
func (c *runServiceClient) ListRuns(ctx context.Context, req *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// StopRun calls agentcompose.v2.RunService.StopRun.
func (c *runServiceClient) StopRun(ctx context.Context, req *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// WatchRun calls agentcompose.v2.RunService.WatchRun.
func (c *runServiceClient) WatchRun(ctx context.Context, req *connect.Request[v2.WatchRunRequest]) (*connect.ServerStreamForClient[v2.RunStreamResponse], error) {
	return c.watchRun.CallServerStream(ctx, req)
}

// RunServiceHandler is an implementation of the agentcompose.v2.RunService service.
type RunServiceHandler interface {
	InvokeService(context.Context, *connect.Request[v2.InvokeServiceRequest]) (*connect.Response[v2.InvokeServiceResponse], error)
	InvokeServiceStream(context.Context, *connect.Request[v2.InvokeServiceRequest], *connect.ServerStream[v2.RunStreamResponse]) error
	RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error)
	RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest], *connect.ServerStream[v2.RunAgentStreamResponse]) error
	GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error)
	ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error)
	StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error)
	WatchRun(context.Context, *connect.Request[v2.WatchRunRequest], *connect.ServerStream[v2.RunStreamResponse]) error
}

// NewRunServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunServiceHandler(svc RunServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("RunService").Methods()
	runServiceInvokeServiceHandler := connect.NewUnaryHandler(
		RunServiceInvokeServiceProcedure,
		svc.InvokeService,
		connect.WithSchema(runServiceMethods.ByName("InvokeService")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceInvokeServiceStreamHandler := connect.NewServerStreamHandler(
		RunServiceInvokeServiceStreamProcedure,
		svc.InvokeServiceStream,
		connect.WithSchema(runServiceMethods.ByName("InvokeServiceStream")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceRunAgentHandler := connect.NewUnaryHandler(
		RunServiceRunAgentProcedure,
		svc.RunAgent,
		connect.WithSchema(runServiceMethods.ByName("RunAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceRunAgentStreamHandler := connect.NewServerStreamHandler(
		RunServiceRunAgentStreamProcedure,
		svc.RunAgentStream,
		connect.WithSchema(runServiceMethods.ByName("RunAgentStream")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceGetRunHandler := connect.NewUnaryHandler(
		RunServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(runServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceListRunsHandler := connect.NewUnaryHandler(
		RunServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(runServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceStopRunHandler := connect.NewUnaryHandler(
		RunServiceStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(runServiceMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceWatchRunHandler := connect.NewServerStreamHandler(
		RunServiceWatchRunProcedure,
		svc.WatchRun,
		connect.WithSchema(runServiceMethods.ByName("WatchRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.RunService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunServiceInvokeServiceProcedure:
			runServiceInvokeServiceHandler.ServeHTTP(w, r)
		case RunServiceInvokeServiceStreamProcedure:
			runServiceInvokeServiceStreamHandler.ServeHTTP(w, r)
		case RunServiceRunAgentProcedure:
			runServiceRunAgentHandler.ServeHTTP(w, r)
		case RunServiceRunAgentStreamProcedure:
			runServiceRunAgentStreamHandler.ServeHTTP(w, r)
		case RunServiceGetRunProcedure:
			runServiceGetRunHandler.ServeHTTP(w, r)
		case RunServiceListRunsProcedure:
			runServiceListRunsHandler.ServeHTTP(w, r)
		case RunServiceStopRunProcedure:
			runServiceStopRunHandler.ServeHTTP(w, r)
		case RunServiceWatchRunProcedure:
			runServiceWatchRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunServiceHandler struct{}

func (UnimplementedRunServiceHandler) InvokeService(context.Context, *connect.Request[v2.InvokeServiceRequest]) (*connect.Response[v2.InvokeServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.InvokeService is not implemented"))
}

func (UnimplementedRunServiceHandler) InvokeServiceStream(context.Context, *connect.Request[v2.InvokeServiceRequest], *connect.ServerStream[v2.RunStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.InvokeServiceStream is not implemented"))
}

func (UnimplementedRunServiceHandler) RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.RunAgent is not implemented"))
}

func (UnimplementedRunServiceHandler) RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest], *connect.ServerStream[v2.RunAgentStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.RunAgentStream is not implemented"))
}

func (UnimplementedRunServiceHandler) GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.GetRun is not implemented"))
}

func (UnimplementedRunServiceHandler) ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.ListRuns is not implemented"))
}

func (UnimplementedRunServiceHandler) StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.StopRun is not implemented"))
}

func (UnimplementedRunServiceHandler) WatchRun(context.Context, *connect.Request[v2.WatchRunRequest], *connect.ServerStream[v2.RunStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.WatchRun is not implemented"))
}

// ArtifactServiceClient is a client for the agentcompose.v2.ArtifactService service.
type ArtifactServiceClient interface {
	ListArtifacts(context.Context, *connect.Request[v2.ListArtifactsRequest]) (*connect.Response[v2.ListArtifactsResponse], error)
	GetArtifact(context.Context, *connect.Request[v2.GetArtifactRequest]) (*connect.Response[v2.GetArtifactResponse], error)
	ReadArtifact(context.Context, *connect.Request[v2.ReadArtifactRequest]) (*connect.Response[v2.ReadArtifactResponse], error)
	WriteArtifact(context.Context, *connect.Request[v2.WriteArtifactRequest]) (*connect.Response[v2.WriteArtifactResponse], error)
	DeleteArtifact(context.Context, *connect.Request[v2.DeleteArtifactRequest]) (*connect.Response[v2.DeleteArtifactResponse], error)
}

// NewArtifactServiceClient constructs a client for the agentcompose.v2.ArtifactService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		listArtifacts: connect.NewClient[v2.ListArtifactsRequest, v2.ListArtifactsResponse](
			httpClient,
			baseURL+ArtifactServiceListArtifactsProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("ListArtifacts")),
			connect.WithClientOptions(opts...),
		),
		getArtifact: connect.NewClient[v2.GetArtifactRequest, v2.GetArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceGetArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("GetArtifact")),
			connect.WithClientOptions(opts...),
		),
		readArtifact: connect.NewClient[v2.ReadArtifactRequest, v2.ReadArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceReadArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("ReadArtifact")),
			connect.WithClientOptions(opts...),
		),
		writeArtifact: connect.NewClient[v2.WriteArtifactRequest, v2.WriteArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceWriteArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("WriteArtifact")),
			connect.WithClientOptions(opts...),
		),
		deleteArtifact: connect.NewClient[v2.DeleteArtifactRequest, v2.DeleteArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceDeleteArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("DeleteArtifact")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	listArtifacts  *connect.Client[v2.ListArtifactsRequest, v2.ListArtifactsResponse]
	getArtifact    *connect.Client[v2.GetArtifactRequest, v2.GetArtifactResponse]
	readArtifact   *connect.Client[v2.ReadArtifactRequest, v2.ReadArtifactResponse]
	writeArtifact  *connect.Client[v2.WriteArtifactRequest, v2.WriteArtifactResponse]
	deleteArtifact *connect.Client[v2.DeleteArtifactRequest, v2.DeleteArtifactResponse]
}

// ListArtifacts calls agentcompose.v2.ArtifactService.ListArtifacts.
func (c *artifactServiceClient) ListArtifacts(ctx context.Context, req *connect.Request[v2.ListArtifactsRequest]) (*connect.Response[v2.ListArtifactsResponse], error) {
	return c.listArtifacts.CallUnary(ctx, req)
}

// GetArtifact calls agentcompose.v2.ArtifactService.GetArtifact.
func (c *artifactServiceClient) GetArtifact(ctx context.Context, req *connect.Request[v2.GetArtifactRequest]) (*connect.Response[v2.GetArtifactResponse], error) {
	return c.getArtifact.CallUnary(ctx, req)
}

// ReadArtifact calls agentcompose.v2.ArtifactService.ReadArtifact.
func (c *artifactServiceClient) ReadArtifact(ctx context.Context, req *connect.Request[v2.ReadArtifactRequest]) (*connect.Response[v2.ReadArtifactResponse], error) {
	return c.readArtifact.CallUnary(ctx, req)
}

// WriteArtifact calls agentcompose.v2.ArtifactService.WriteArtifact.
func (c *artifactServiceClient) WriteArtifact(ctx context.Context, req *connect.Request[v2.WriteArtifactRequest]) (*connect.Response[v2.WriteArtifactResponse], error) {
	return c.writeArtifact.CallUnary(ctx, req)
}

// DeleteArtifact calls agentcompose.v2.ArtifactService.DeleteArtifact.
func (c *artifactServiceClient) DeleteArtifact(ctx context.Context, req *connect.Request[v2.DeleteArtifactRequest]) (*connect.Response[v2.DeleteArtifactResponse], error) {
	return c.deleteArtifact.CallUnary(ctx, req)
}

// ArtifactServiceHandler is an implementation of the agentcompose.v2.ArtifactService service.
type ArtifactServiceHandler interface {
	ListArtifacts(context.Context, *connect.Request[v2.ListArtifactsRequest]) (*connect.Response[v2.ListArtifactsResponse], error)
	GetArtifact(context.Context, *connect.Request[v2.GetArtifactRequest]) (*connect.Response[v2.GetArtifactResponse], error)
	ReadArtifact(context.Context, *connect.Request[v2.ReadArtifactRequest]) (*connect.Response[v2.ReadArtifactResponse], error)
	WriteArtifact(context.Context, *connect.Request[v2.WriteArtifactRequest]) (*connect.Response[v2.WriteArtifactResponse], error)
	DeleteArtifact(context.Context, *connect.Request[v2.DeleteArtifactRequest]) (*connect.Response[v2.DeleteArtifactResponse], error)
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceListArtifactsHandler := connect.NewUnaryHandler(
		ArtifactServiceListArtifactsProcedure,
		svc.ListArtifacts,
		connect.WithSchema(artifactServiceMethods.ByName("ListArtifacts")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceGetArtifactHandler := connect.NewUnaryHandler(
		ArtifactServiceGetArtifactProcedure,
		svc.GetArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("GetArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceReadArtifactHandler := connect.NewUnaryHandler(
		ArtifactServiceReadArtifactProcedure,
		svc.ReadArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("ReadArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceWriteArtifactHandler := connect.NewUnaryHandler(
		ArtifactServiceWriteArtifactProcedure,
		svc.WriteArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("WriteArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceDeleteArtifactHandler := connect.NewUnaryHandler(
		ArtifactServiceDeleteArtifactProcedure,
		svc.DeleteArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("DeleteArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceListArtifactsProcedure:
			artifactServiceListArtifactsHandler.ServeHTTP(w, r)
		case ArtifactServiceGetArtifactProcedure:
			artifactServiceGetArtifactHandler.ServeHTTP(w, r)
		case ArtifactServiceReadArtifactProcedure:
			artifactServiceReadArtifactHandler.ServeHTTP(w, r)
		case ArtifactServiceWriteArtifactProcedure:
			artifactServiceWriteArtifactHandler.ServeHTTP(w, r)
		case ArtifactServiceDeleteArtifactProcedure:
			artifactServiceDeleteArtifactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) ListArtifacts(context.Context, *connect.Request[v2.ListArtifactsRequest]) (*connect.Response[v2.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ArtifactService.ListArtifacts is not implemented"))
}

func (UnimplementedArtifactServiceHandler) GetArtifact(context.Context, *connect.Request[v2.GetArtifactRequest]) (*connect.Response[v2.GetArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ArtifactService.GetArtifact is not implemented"))
}

func (UnimplementedArtifactServiceHandler) ReadArtifact(context.Context, *connect.Request[v2.ReadArtifactRequest]) (*connect.Response[v2.ReadArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ArtifactService.ReadArtifact is not implemented"))
}

func (UnimplementedArtifactServiceHandler) WriteArtifact(context.Context, *connect.Request[v2.WriteArtifactRequest]) (*connect.Response[v2.WriteArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ArtifactService.WriteArtifact is not implemented"))
}

func (UnimplementedArtifactServiceHandler) DeleteArtifact(context.Context, *connect.Request[v2.DeleteArtifactRequest]) (*connect.Response[v2.DeleteArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ArtifactService.DeleteArtifact is not implemented"))
}

// EventServiceClient is a client for the agentcompose.v2.EventService service.
type EventServiceClient interface {
	PublishEvent(context.Context, *connect.Request[v2.PublishEventRequest]) (*connect.Response[v2.PublishEventResponse], error)
	ListEvents(context.Context, *connect.Request[v2.ListEventsRequest]) (*connect.Response[v2.ListEventsResponse], error)
	WatchEvents(context.Context, *connect.Request[v2.WatchEventsRequest]) (*connect.ServerStreamForClient[v2.EventRecord], error)
}

// NewEventServiceClient constructs a client for the agentcompose.v2.EventService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		publishEvent: connect.NewClient[v2.PublishEventRequest, v2.PublishEventResponse](
			httpClient,
			baseURL+EventServicePublishEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("PublishEvent")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v2.ListEventsRequest, v2.ListEventsResponse](
			httpClient,
			baseURL+EventServiceListEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		watchEvents: connect.NewClient[v2.WatchEventsRequest, v2.EventRecord](
			httpClient,
			baseURL+EventServiceWatchEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("WatchEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	publishEvent *connect.Client[v2.PublishEventRequest, v2.PublishEventResponse]
	listEvents   *connect.Client[v2.ListEventsRequest, v2.ListEventsResponse]
	watchEvents  *connect.Client[v2.WatchEventsRequest, v2.EventRecord]
}

// PublishEvent calls agentcompose.v2.EventService.PublishEvent.
func (c *eventServiceClient) PublishEvent(ctx context.Context, req *connect.Request[v2.PublishEventRequest]) (*connect.Response[v2.PublishEventResponse], error) {
	return c.publishEvent.CallUnary(ctx, req)
}

// ListEvents calls agentcompose.v2.EventService.ListEvents.
func (c *eventServiceClient) ListEvents(ctx context.Context, req *connect.Request[v2.ListEventsRequest]) (*connect.Response[v2.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// WatchEvents calls agentcompose.v2.EventService.WatchEvents.
func (c *eventServiceClient) WatchEvents(ctx context.Context, req *connect.Request[v2.WatchEventsRequest]) (*connect.ServerStreamForClient[v2.EventRecord], error) {
	return c.watchEvents.CallServerStream(ctx, req)
}

// EventServiceHandler is an implementation of the agentcompose.v2.EventService service.
type EventServiceHandler interface {
	PublishEvent(context.Context, *connect.Request[v2.PublishEventRequest]) (*connect.Response[v2.PublishEventResponse], error)
	ListEvents(context.Context, *connect.Request[v2.ListEventsRequest]) (*connect.Response[v2.ListEventsResponse], error)
	WatchEvents(context.Context, *connect.Request[v2.WatchEventsRequest], *connect.ServerStream[v2.EventRecord]) error
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("EventService").Methods()
	eventServicePublishEventHandler := connect.NewUnaryHandler(
		EventServicePublishEventProcedure,
		svc.PublishEvent,
		connect.WithSchema(eventServiceMethods.ByName("PublishEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListEventsHandler := connect.NewUnaryHandler(
		EventServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceWatchEventsHandler := connect.NewServerStreamHandler(
		EventServiceWatchEventsProcedure,
		svc.WatchEvents,
		connect.WithSchema(eventServiceMethods.ByName("WatchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServicePublishEventProcedure:
			eventServicePublishEventHandler.ServeHTTP(w, r)
		case EventServiceListEventsProcedure:
			eventServiceListEventsHandler.ServeHTTP(w, r)
		case EventServiceWatchEventsProcedure:
			eventServiceWatchEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) PublishEvent(context.Context, *connect.Request[v2.PublishEventRequest]) (*connect.Response[v2.PublishEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.EventService.PublishEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) ListEvents(context.Context, *connect.Request[v2.ListEventsRequest]) (*connect.Response[v2.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.EventService.ListEvents is not implemented"))
}

func (UnimplementedEventServiceHandler) WatchEvents(context.Context, *connect.Request[v2.WatchEventsRequest], *connect.ServerStream[v2.EventRecord]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.EventService.WatchEvents is not implemented"))
}

// ExecServiceClient is a client for the agentcompose.v2.ExecService service.
type ExecServiceClient interface {
	Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error)
	ExecStream(context.Context, *connect.Request[v2.ExecRequest]) (*connect.ServerStreamForClient[v2.ExecStreamResponse], error)
}

// NewExecServiceClient constructs a client for the agentcompose.v2.ExecService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	execServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ExecService").Methods()
	return &execServiceClient{
		exec: connect.NewClient[v2.ExecRequest, v2.ExecResponse](
			httpClient,
			baseURL+ExecServiceExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		execStream: connect.NewClient[v2.ExecRequest, v2.ExecStreamResponse](
			httpClient,
			baseURL+ExecServiceExecStreamProcedure,
			connect.WithSchema(execServiceMethods.ByName("ExecStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// execServiceClient implements ExecServiceClient.
type execServiceClient struct {
	exec       *connect.Client[v2.ExecRequest, v2.ExecResponse]
	execStream *connect.Client[v2.ExecRequest, v2.ExecStreamResponse]
}

// Exec calls agentcompose.v2.ExecService.Exec.
func (c *execServiceClient) Exec(ctx context.Context, req *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// ExecStream calls agentcompose.v2.ExecService.ExecStream.
func (c *execServiceClient) ExecStream(ctx context.Context, req *connect.Request[v2.ExecRequest]) (*connect.ServerStreamForClient[v2.ExecStreamResponse], error) {
	return c.execStream.CallServerStream(ctx, req)
}

// ExecServiceHandler is an implementation of the agentcompose.v2.ExecService service.
type ExecServiceHandler interface {
	Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error)
	ExecStream(context.Context, *connect.Request[v2.ExecRequest], *connect.ServerStream[v2.ExecStreamResponse]) error
}

// NewExecServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecServiceHandler(svc ExecServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	execServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ExecService").Methods()
	execServiceExecHandler := connect.NewUnaryHandler(
		ExecServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(execServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	execServiceExecStreamHandler := connect.NewServerStreamHandler(
		ExecServiceExecStreamProcedure,
		svc.ExecStream,
		connect.WithSchema(execServiceMethods.ByName("ExecStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ExecService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecServiceExecProcedure:
			execServiceExecHandler.ServeHTTP(w, r)
		case ExecServiceExecStreamProcedure:
			execServiceExecStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecServiceHandler struct{}

func (UnimplementedExecServiceHandler) Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ExecService.Exec is not implemented"))
}

func (UnimplementedExecServiceHandler) ExecStream(context.Context, *connect.Request[v2.ExecRequest], *connect.ServerStream[v2.ExecStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ExecService.ExecStream is not implemented"))
}

// ImageServiceClient is a client for the agentcompose.v2.ImageService service.
type ImageServiceClient interface {
	ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error)
	PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error)
	InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error)
	RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error)
}

// NewImageServiceClient constructs a client for the agentcompose.v2.ImageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	imageServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ImageService").Methods()
	return &imageServiceClient{
		listImages: connect.NewClient[v2.ListImagesRequest, v2.ListImagesResponse](
			httpClient,
			baseURL+ImageServiceListImagesProcedure,
			connect.WithSchema(imageServiceMethods.ByName("ListImages")),
			connect.WithClientOptions(opts...),
		),
		pullImage: connect.NewClient[v2.PullImageRequest, v2.PullImageResponse](
			httpClient,
			baseURL+ImageServicePullImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("PullImage")),
			connect.WithClientOptions(opts...),
		),
		inspectImage: connect.NewClient[v2.InspectImageRequest, v2.InspectImageResponse](
			httpClient,
			baseURL+ImageServiceInspectImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("InspectImage")),
			connect.WithClientOptions(opts...),
		),
		removeImage: connect.NewClient[v2.RemoveImageRequest, v2.RemoveImageResponse](
			httpClient,
			baseURL+ImageServiceRemoveImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("RemoveImage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageServiceClient implements ImageServiceClient.
type imageServiceClient struct {
	listImages   *connect.Client[v2.ListImagesRequest, v2.ListImagesResponse]
	pullImage    *connect.Client[v2.PullImageRequest, v2.PullImageResponse]
	inspectImage *connect.Client[v2.InspectImageRequest, v2.InspectImageResponse]
	removeImage  *connect.Client[v2.RemoveImageRequest, v2.RemoveImageResponse]
}

// ListImages calls agentcompose.v2.ImageService.ListImages.
func (c *imageServiceClient) ListImages(ctx context.Context, req *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error) {
	return c.listImages.CallUnary(ctx, req)
}

// PullImage calls agentcompose.v2.ImageService.PullImage.
func (c *imageServiceClient) PullImage(ctx context.Context, req *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error) {
	return c.pullImage.CallUnary(ctx, req)
}

// InspectImage calls agentcompose.v2.ImageService.InspectImage.
func (c *imageServiceClient) InspectImage(ctx context.Context, req *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error) {
	return c.inspectImage.CallUnary(ctx, req)
}

// RemoveImage calls agentcompose.v2.ImageService.RemoveImage.
func (c *imageServiceClient) RemoveImage(ctx context.Context, req *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error) {
	return c.removeImage.CallUnary(ctx, req)
}

// ImageServiceHandler is an implementation of the agentcompose.v2.ImageService service.
type ImageServiceHandler interface {
	ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error)
	PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error)
	InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error)
	RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error)
}

// NewImageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageServiceHandler(svc ImageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageServiceMethods := v2.File_agentcompose_v2_agentcompose_proto.Services().ByName("ImageService").Methods()
	imageServiceListImagesHandler := connect.NewUnaryHandler(
		ImageServiceListImagesProcedure,
		svc.ListImages,
		connect.WithSchema(imageServiceMethods.ByName("ListImages")),
		connect.WithHandlerOptions(opts...),
	)
	imageServicePullImageHandler := connect.NewUnaryHandler(
		ImageServicePullImageProcedure,
		svc.PullImage,
		connect.WithSchema(imageServiceMethods.ByName("PullImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceInspectImageHandler := connect.NewUnaryHandler(
		ImageServiceInspectImageProcedure,
		svc.InspectImage,
		connect.WithSchema(imageServiceMethods.ByName("InspectImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceRemoveImageHandler := connect.NewUnaryHandler(
		ImageServiceRemoveImageProcedure,
		svc.RemoveImage,
		connect.WithSchema(imageServiceMethods.ByName("RemoveImage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ImageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageServiceListImagesProcedure:
			imageServiceListImagesHandler.ServeHTTP(w, r)
		case ImageServicePullImageProcedure:
			imageServicePullImageHandler.ServeHTTP(w, r)
		case ImageServiceInspectImageProcedure:
			imageServiceInspectImageHandler.ServeHTTP(w, r)
		case ImageServiceRemoveImageProcedure:
			imageServiceRemoveImageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageServiceHandler struct{}

func (UnimplementedImageServiceHandler) ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.ListImages is not implemented"))
}

func (UnimplementedImageServiceHandler) PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.PullImage is not implemented"))
}

func (UnimplementedImageServiceHandler) InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.InspectImage is not implemented"))
}

func (UnimplementedImageServiceHandler) RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.RemoveImage is not implemented"))
}
